/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Fob bundler for Node.js */
export declare class Fob {
  /** Create a new bundler instance */
  constructor(config: BundleConfig);
  /** Bundle the configured entries and return detailed bundle information */
  bundle(): Promise<BundleResult>;
}

/** Asset information */
export interface AssetInfo {
  publicPath: string;
  relativePath: string;
  size: number;
  format?: string;
}

/** Build statistics */
export interface BuildStatsInfo {
  totalModules: number;
  totalChunks: number;
  totalSize: number;
  durationMs: number;
  cacheHitRate: number;
}

/** Bundle configuration */
export interface BundleConfig {
  /** Entry points to bundle */
  entries: Array<string>;
  /** Output directory (defaults to "dist" if not provided) */
  outputDir?: string;
  /** Output format ("esm" | "cjs" | "iife") */
  format?: OutputFormat;
  /**
   * Source map generation mode
   * Can be a boolean string ("true" = external, "false" = disabled) or a mode string ("inline" | "hidden" | "external")
   * In JavaScript/TypeScript, pass as string: "true", "false", "inline", "hidden", or "external"
   */
  sourcemap?: string;
  /** Packages to externalize (not bundled) */
  external?: Array<string>;
  /** Target platform ("browser" | "node", default: "browser") */
  platform?: string;
  /** Enable minification (default: false) */
  minify?: boolean;
  /** Working directory for resolution */
  cwd?: string;
  /**
   * MDX compilation options
   * If None, MDX is auto-enabled when .mdx entries are detected
   */
  mdx?: MdxOptions;
}

/** Result of a bundle operation */
export interface BundleResult {
  /** Generated chunks */
  chunks: Array<ChunkInfo>;
  /** Bundle manifest */
  manifest: ManifestInfo;
  /** Build statistics */
  stats: BuildStatsInfo;
  /** Static assets */
  assets: Array<AssetInfo>;
  /** Total module count (convenience field) */
  moduleCount: number;
}

/** Quick helper to bundle a single entry */
export declare function bundleSingle(
  entry: string,
  outputDir: string,
  format?: OutputFormat | undefined | null
): Promise<BundleResult>;

/** Detailed chunk information */
export interface ChunkInfo {
  /** Chunk identifier */
  id: string;
  /** Chunk type: "entry" | "async" | "shared" */
  kind: string;
  /** Output file name */
  fileName: string;
  /** Generated code */
  code: string;
  /** Source map (optional) */
  sourceMap?: string;
  /** Modules in this chunk */
  modules: Array<ModuleInfo>;
  /** Static imports */
  imports: Array<string>;
  /** Dynamic imports */
  dynamicImports: Array<string>;
  /** Size in bytes */
  size: number;
}

/** Chunk metadata */
export interface ChunkMetadata {
  file: string;
  imports: Array<string>;
  dynamicImports: Array<string>;
  css: Array<string>;
}

/**
 * Initialize fob logging with specified level
 *
 * Call this once at application startup before any fob operations.
 * It is safe to call multiple times - only the first call takes effect.
 *
 * @example
 * ```typescript
 * import { initLogging } from '@fob/native';
 *
 * initLogging('info');
 * // or
 * initLogging('debug');
 * ```
 */
export declare function initLogging(level?: LogLevel | undefined | null): void;

/**
 * Initialize logging from RUST_LOG environment variable
 *
 * Falls back to Info level if RUST_LOG is not set or invalid.
 * Call this once at application startup before any fob operations.
 *
 * @example
 * ```typescript
 * import { initLoggingFromEnv } from '@fob/native';
 *
 * // Set RUST_LOG=fob=debug before running
 * initLoggingFromEnv();
 * ```
 */
export declare function initLoggingFromEnv(): void;

/**
 * Log level for fob output
 *
 * Controls the verbosity of logging during bundling operations.
 */
export declare const enum LogLevel {
  /** No logging output */
  Silent = 'Silent',
  /** Only errors */
  Error = 'Error',
  /** Errors and warnings */
  Warn = 'Warn',
  /** Errors, warnings, and info (default) */
  Info = 'Info',
  /** All logs including debug */
  Debug = 'Debug',
}

/** Bundle manifest */
export interface ManifestInfo {
  /** Entry mappings */
  entries: Record<string, string>;
  /** Chunk metadata */
  chunks: Record<string, ChunkMetadata>;
  /** Version */
  version: string;
}

/**
 * MDX compilation options
 *
 * Configure how MDX files are compiled to JSX. All options are optional
 * and have sensible defaults. MDX is auto-enabled when .mdx entries are detected.
 */
export interface MdxOptions {
  /**
   * Enable GitHub Flavored Markdown (tables, strikethrough, task lists)
   * Default: true
   */
  gfm?: boolean;
  /**
   * Enable footnotes
   * Default: true
   */
  footnotes?: boolean;
  /**
   * Enable math support ($inline$ and $$block$$)
   * Default: true
   */
  math?: boolean;
  /**
   * JSX runtime module path
   * Default: "react/jsx-runtime"
   */
  jsxRuntime?: string;
  /**
   * Use default plugins (heading IDs, image optimization)
   * Default: true
   */
  useDefaultPlugins?: boolean;
}

/** Module information */
export interface ModuleInfo {
  /** Module path */
  path: string;
  /** Module size in bytes (None if unavailable) */
  size?: number;
  /** Has side effects (None if unavailable) */
  hasSideEffects?: boolean;
}

/** Output format for bundled code */
export declare const enum OutputFormat {
  /** ES Module format */
  Esm = 'Esm',
  /** CommonJS format */
  Cjs = 'Cjs',
  /** Immediately Invoked Function Expression format */
  Iife = 'Iife',
}

/** Get the bundler version */
export declare function version(): string;
