/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Fob bundler for Node.js */
export declare class Fob {
  /** Create a new bundler instance with full configuration control. */
  constructor(config: BundleConfig)
  /** Bundle the configured entries and return detailed bundle information. */
  bundle(): Promise<BundleResult>
  /**
   * Build a standalone bundle (single entry, full bundling).
   *
   * Best for: Applications, scripts, or single-file outputs.
   *
   * ```typescript
   * const result = await Fob.bundleEntry("src/index.ts", { outDir: "dist" });
   * ```
   */
  static bundleEntry(entry: string, options?: BuildOptions | undefined | null): Promise<BundleResult>
  /**
   * Build a library (single entry, externalize dependencies).
   *
   * Best for: npm packages, reusable libraries.
   * Dependencies are marked as external and not bundled.
   *
   * ```typescript
   * const result = await Fob.library("src/index.ts", {
   *   outDir: "dist",
   *   external: ["react", "react-dom"]
   * });
   * ```
   */
  static library(entry: string, options?: BuildOptions | undefined | null): Promise<BundleResult>
  /**
   * Build an app with code splitting (multiple entries, unified output).
   *
   * Best for: Web applications with multiple pages/routes.
   * Shared dependencies are extracted into common chunks.
   *
   * ```typescript
   * const result = await Fob.app(["src/client.tsx", "src/worker.ts"], {
   *   outDir: "dist",
   *   chunking: { minSize: 20000, minShareCount: 2 }
   * });
   * ```
   */
  static app(entries: Array<string>, options?: AppOptions | undefined | null): Promise<BundleResult>
  /**
   * Build a component library (multiple entries, separate bundles).
   *
   * Best for: UI component libraries, design systems.
   * Each entry produces an independent bundle with no shared chunks.
   *
   * ```typescript
   * const result = await Fob.components(["src/Button.tsx", "src/Card.tsx"], {
   *   outDir: "dist"
   * });
   * ```
   */
  static components(entries: Array<string>, options?: BuildOptions | undefined | null): Promise<BundleResult>
}

/** Options for app builds with code splitting. */
export interface AppOptions {
  /** Output directory (defaults to "dist") */
  outDir?: string
  /** Output format: "esm" (default), "cjs", or "iife" */
  format?: string
  /** Source map generation: "true", "false", "inline", "hidden" */
  sourcemap?: string
  /** Packages to externalize */
  external?: Array<string>
  /** Target platform: "browser" (default) or "node" */
  platform?: string
  /** Enable minification */
  minify?: boolean
  /** Working directory for resolution */
  cwd?: string
  /** Code splitting configuration */
  codeSplitting?: CodeSplittingConfig
}

/** Asset information */
export interface AssetInfo {
  publicPath: string
  relativePath: string
  size: number
  format?: string
}

/** Common build options shared by preset functions. */
export interface BuildOptions {
  /** Output directory (defaults to "dist") */
  outDir?: string
  /** Output format: "esm" (default), "cjs", or "iife" */
  format?: string
  /** Source map generation: "true", "false", "inline", "hidden" */
  sourcemap?: string
  /** Packages to externalize (not bundled) */
  external?: Array<string>
  /** Target platform: "browser" (default) or "node" */
  platform?: string
  /** Enable minification */
  minify?: boolean
  /** Working directory for resolution */
  cwd?: string
}

/** Build statistics */
export interface BuildStatsInfo {
  totalModules: number
  totalChunks: number
  totalSize: number
  durationMs: number
  cacheHitRate: number
}

/** Bundle configuration */
export interface BundleConfig {
  /** Entry points to bundle */
  entries: Array<string>
  /** Output directory (defaults to "dist" if not provided) */
  outputDir?: string
  /** Output format: "esm" | "cjs" | "iife" (case-insensitive, default: "esm") */
  format?: string
  /**
   * Source map generation mode
   * Accepts: "true", "false", "external", "inline", "hidden"
   * Default: disabled (no source maps)
   */
  sourcemap?: string
  /** Target platform ("browser" | "node", default: "browser") */
  platform?: string
  /** Enable minification (default: false) */
  minify?: boolean
  /** Working directory for resolution */
  cwd?: string
  /**
   * MDX compilation options
   * If None, MDX is auto-enabled when .mdx entries are detected
   */
  mdx?: MdxOptions
  /**
   * Entry mode: "shared" | "isolated" (case-insensitive, default: "shared")
   * - shared: Entries can share chunks
   * - isolated: Each entry stands alone
   */
  entryMode?: string
  /**
   * Code splitting configuration
   * - None/undefined: No code splitting
   * - Object: Enable code splitting with specified thresholds
   */
  codeSplitting?: CodeSplittingConfig
  /**
   * External packages (simplified for JS)
   * - None/undefined: Bundle everything
   * - Array: Externalize specific packages
   */
  external?: Array<string>
  /**
   * Externalize dependencies from package.json manifest
   * - true: Read dependencies/peerDependencies from package.json
   * - false/undefined: Use explicit external list or bundle all
   */
  externalFromManifest?: boolean
  /**
   * Virtual files mapping (path → content)
   * Used internally when entries have inline content via the JS wrapper.
   * Keys should use "virtual:" prefix (e.g., "virtual:main.ts")
   */
  virtualFiles?: Record<string, string>
}

/** Result of a bundle operation */
export interface BundleResult {
  /** Generated chunks */
  chunks: Array<ChunkInfo>
  /** Bundle manifest */
  manifest: ManifestInfo
  /** Build statistics */
  stats: BuildStatsInfo
  /** Static assets */
  assets: Array<AssetInfo>
  /** Total module count (convenience field) */
  moduleCount: number
}

/**
 * Quick helper to bundle a single entry
 *
 * @param format - "esm" | "cjs" | "iife" (case-insensitive, default: "esm")
 */
export declare function bundleSingle(entry: string, outputDir: string, format?: string | undefined | null): Promise<BundleResult>

/** Detailed chunk information */
export interface ChunkInfo {
  /** Chunk identifier */
  id: string
  /** Chunk type: "entry" | "async" | "shared" */
  kind: string
  /** Output file name */
  fileName: string
  /** Generated code */
  code: string
  /** Source map (optional) */
  sourceMap?: string
  /** Modules in this chunk */
  modules: Array<ModuleInfo>
  /** Static imports */
  imports: Array<string>
  /** Dynamic imports */
  dynamicImports: Array<string>
  /** Size in bytes */
  size: number
}

/** Chunk metadata */
export interface ChunkMetadata {
  file: string
  imports: Array<string>
  dynamicImports: Array<string>
  css: Array<string>
}

/**
 * Configuration for code splitting.
 *
 * Code splitting extracts shared dependencies into separate chunks.
 */
export interface CodeSplittingConfig {
  /** Minimum chunk size in bytes (default: 20000 = 20KB) */
  minSize: number
  /**
   * Minimum number of entry points that must import the same module (default: 2)
   *
   * This was previously called `min_share_count` but `min_imports` is clearer
   * about what's being counted.
   */
  minImports: number
}

/**
 * Initialize fob logging with specified level
 *
 * Call this once at application startup before any fob operations.
 * It is safe to call multiple times - only the first call takes effect.
 *
 * @param level - "silent" | "error" | "warn" | "info" | "debug" (case-insensitive, default: "info")
 *
 * @example
 * ```typescript
 * import { initLogging } from '@fob/native';
 *
 * initLogging('info');
 * // or
 * initLogging('debug');
 * ```
 */
export declare function initLogging(level?: string | undefined | null): void

/**
 * Initialize logging from RUST_LOG environment variable
 *
 * Falls back to Info level if RUST_LOG is not set or invalid.
 * Call this once at application startup before any fob operations.
 *
 * @example
 * ```typescript
 * import { initLoggingFromEnv } from '@fob/native';
 *
 * // Set RUST_LOG=fob=debug before running
 * initLoggingFromEnv();
 * ```
 */
export declare function initLoggingFromEnv(): void

/** Bundle manifest */
export interface ManifestInfo {
  /** Entry mappings */
  entries: Record<string, string>
  /** Chunk metadata */
  chunks: Record<string, ChunkMetadata>
  /** Version */
  version: string
}

/**
 * MDX compilation options
 *
 * Configure how MDX files are compiled to JSX. All options are optional
 * and have sensible defaults. MDX is auto-enabled when .mdx entries are detected.
 */
export interface MdxOptions {
  /**
   * Enable GitHub Flavored Markdown (tables, strikethrough, task lists)
   * Default: true
   */
  gfm?: boolean
  /**
   * Enable footnotes
   * Default: true
   */
  footnotes?: boolean
  /**
   * Enable math support ($inline$ and $$block$$)
   * Default: true
   */
  math?: boolean
  /**
   * JSX runtime module path
   * Default: "react/jsx-runtime"
   */
  jsxRuntime?: string
  /**
   * Use default plugins (heading IDs, image optimization)
   * Default: true
   */
  useDefaultPlugins?: boolean
}

/** Module information */
export interface ModuleInfo {
  /** Module path */
  path: string
  /** Module size in bytes (None if unavailable) */
  size?: number
  /** Has side effects (None if unavailable) */
  hasSideEffects?: boolean
}

/** Get the bundler version */
export declare function version(): string
