// Lightweight wrapper to expose stable named exports around the autogenerated NAPI binding.
// The generated index.js may change on rebuilds, so keep custom exports here.
const binding = require('./index.js');

const OutputFormat = Object.freeze({
  Esm: 'esm',
  Cjs: 'cjs',
  Iife: 'iife',
});

const SourceMapMode = Object.freeze({
  External: 'external',
  Inline: 'inline',
  Hidden: 'hidden',
  Disabled: 'false',
});

module.exports = {
  ...binding,
  OutputFormat,
  SourceMapMode,
};
