# fob-php development commands

# Default recipe - show available commands
default:
    @just --list

# Build debug
build:
    cargo build --package fob-php

# Build release
build-release:
    cargo build --release --package fob-php

# Check compilation
check:
    cargo check --package fob-php

# Run clippy
clippy:
    cargo clippy --package fob-php

# Run example (builds release first)
example: build-release
    php -d extension=../../target/release/libfob.dylib ../../examples/php/fob-simple/bundler.php

# Test extension loads
test-load:
    php -d extension=../../target/release/libfob.dylib -r "var_dump(extension_loaded('fob-php'));"

# List exported functions
list-functions:
    php -d extension=../../target/release/libfob.dylib -r "print_r(get_extension_funcs('fob-php'));"

# Show version
version:
    php -d extension=../../target/release/libfob.dylib -r "echo version() . PHP_EOL;"
