# fob-php development commands

default:
    @just --list

build:
    cargo build --package fob-php

build-release:
    cargo build --release --package fob-php

check:
    cargo check --package fob-php

clippy:
    cargo clippy --package fob-php

example: build-release
    php -d extension=../../target/release/libfob_php.dylib ../../examples/php/fob-simple/bundler.php

example-inline: build-release
    php -d extension=../../target/release/libfob_php.dylib ../../examples/php/fob-simple/inline_content.php

test-load: build-release
    php -d extension=../../target/release/libfob_php.dylib -r "var_dump(extension_loaded('fob-php'));"

list-functions: build-release
    php -d extension=../../target/release/libfob_php.dylib -r "print_r(get_extension_funcs('fob-php'));"

version: build-release
    php -d extension=../../target/release/libfob_php.dylib -r "echo version() . PHP_EOL;"
